2.0:Ongeldige parameter\r\n
0.0:    SORT [/R] [/+num] [/?]\r\n
0.1:    /R    Keer volgorde om\r\n
0.2:    /N    Schakel NLS ondersteuning in\r\n
0.3:    /+num Begin met sorteren bij column num, 1 als basisgetal\r\n
0.4:    /?    hulp\r\n
2.1:Fout bij het lezen van de NLS collate tabel\r\n
2.2:Alleen DOS 3.3 of nieuwer ondersteunt NLS!\r\n
2.3:SORT: Kan bestand niet openen
2.4: om te lezen\r\n
2.5:SORT: Onvoldoende geheugen\r\n
2.6:SORT: Aantal records overschrijdt het maximum\r\n
